version: "3.9"
   
services:
  db:
    image: mysql:5.7
    ports:
        - '3306:3306'
    environment:
        MYSQL_DATABASE: 'my-app-db'
        MYSQL_USER: 'kuda'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-p$$MYSQL_PASSWORD"]
        retries: 3
        timeout: 5s
  web:
    build:
        context: ./backend
    volumes:
        - ./backend:/app
    ports:
        - '8000:80'
    env_file:
        - ./backend/.env
    depends_on:
        db:
           condition: service_healthy
  ui:
    build: ./frontend
    container_name: ui
    ports:
        - 8080:80
    links:
        - web
